#!/usr/bin/perl
use vars qw($APP $VERSION);
$APP     = 'set_single_color';
$VERSION = 0.11;

use strict;
use Getopt::Long;
use Pod::Usage;
use Term::ExtendedColor;

our($index, $color) = (0, '9dff00');

GetOptions(
  'index:i' => \$index,
  'color:s' => \$color,
  'help'    => sub { print "$APP $VERSION\n\n"; pod2usage(verbose => 1); exit(0); },
);



my $result = set_color($index, $color);
print "Changing color index $index to color $color\n";
print $result;

=pod

=head1 NAME

  set_single_color

=head1 DESCRIPTION

  set_single_color demonstrates the function with the same name imported from
  Term::ExtendedColor.

=head1 OPTIONS

  -i, --index   index color (0..255) to change
  -c, --color   specify color

  -h, --help    show the help and exit

=head1 AUTHOR

Written by Magnus Woldrich

=head1 REPORTING BUGS

Report bugs to trapd00r@trapd00r.se

=head1 COPYRIGHT

Copyright (C) 2010 Magnus Woldrich

=cut

